### ISSUE TITLE
(Bug) Cannot add G-Key

### ISSUE THREAD

**Issue by Markj2** [CrossVR/gkey_plugin#1]
I cannot add the G-Key to the G5 Button or G4 Button in the Logitech Gaming Software for my Logitech Proteus core not sure if I am doing something wrong.

**Comment by CrossVR** [comment]
For some reason I wasn't notified of your issue report. Is it just the G5 or G4 buttons specifically or is it not possible for you to bind the g-key to anything?

**Comment by Markj2** [comment]
Just G4 and G5 are having problems all the other keys work perfectly.

**Comment by CrossVR** [comment]
Sounds like a bug in the Logitech Gaming Software then? Can you bind any other actions to that key?

**Comment by Markj2** [comment]
I can bind every other kind of action to the 2 keys except the G-Keys from the plugin.

**Comment by CrossVR** [comment]
The G-Key action is not from the plugin, it's just something the Logitech Gaming Software adds for applications that support G-Keys.

It's not something I can fix in the plugin, you should contact Logitech support.

**Comment by Markj2** [comment]
Ok will do

**Comment by Cyirak** [comment]
Hi I've been using your plugin for a while now with my G700s however i've now changed my mouse to a G903 which unfortuanly has less buttons, I'd like to bind gkey to the forward button however i'm unable to. i can bind to dpi up and down button and it works.  are you aware of any work arounds or how i can get this working?

**Comment by CrossVR** [comment]
@Cyirak You have to explicitly assign the G-Key to that mouse button. As shown in this image: https://github.com/Armada651/gkey_plugin/blob/master/lgs_mouse.png

**Comment by Cyirak** [comment]
Hi Thanks for your quick response. I try to drag the g-key to the mouse button and it stays unassigned. if i drag to say dpi up button it will take.

**Comment by CrossVR** [comment]
Then I can only tell you the same thing as I told @Markj2, this is a bug in the Logitsch software, not something I can solve.
