### ISSUE TITLE
Official?

### ISSUE THREAD

**Issue by FlagX** [CrossVR/gkey_plugin#3]
Is this the official repo to the Logitech G-Key Plugin (https://www.myteamspeak.com/addons/68ab6dfb-94a6-497c-b9e3-d14a4ed07955)?
If yes, how long will it take for the latest release until rollout?

Kind regards,
Stefan

**Comment by CrossVR** [comment]
Yes, this is the official repo, you can download the latest release manually here: https://github.com/Armada651/gkey_plugin/releases/tag/v1.1

I've already submitted the updated version, it's now waiting on teamspeak to approve it.

**Comment by FlagX** [comment]
@Armada651 Thanks!
