### ISSUE TITLE
G-Hub support

### ISSUE THREAD

**Issue by floribe2000** [CrossVR/gkey_plugin#4]
Is there a possibility to add G-Hub support? Currently it's only working with the normal Gaming Software but it is not shown in G-Hub. 
Might this feature be added to the plugin?

**Comment by CrossVR** [comment]
Unfortunately Logitech has not released a G-Key SDK for G-Hub. You can see an overview of their SDKs here:

https://www.logitechg.com/en-us/innovation/developer-lab.html
